// Generated by scripts/build-media-manifest.mjs — do not edit by hand.
// Regenerate with: npm run media:index

export interface ManifestEntry {
  url: string;
  name: string;
  folder: string;
  kind: 'image' | 'video';
  bytes: number;
}

export const mediaManifest: ManifestEntry[] = [];
